import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  gettingStartedSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'Getting Started/installation',
        'Getting Started/howtouse',
      ],
    },

    {
      type: 'category',
      label: 'Frontend',
      items: ['Frontend/overview',
              'Frontend/navbar',
              'Frontend/firmware-vault', 
              'Frontend/data-explorer',
              {
                type: 'category',
                label: 'Services',
                items: ['Frontend/Services/dynamicsqlquerybuilder'],
              },
              {
                type: 'category',
                label: 'Integrations',
                items: ['Frontend/Integrations/aggrid'],
              }
            ],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [
        'Backend/introduction', 
        'Backend/implemented-modules', 
        'Backend/wrapper-documentation',
        'Backend/firmwalker'],
    },

    {
      type: 'category',
      label: 'Documentation',
      items: ['Documentation/docusaurus'],
    },
  ],
};

export default sidebars;
